---
- name: ======
  user: name={{ item.name }}
  become: yes
  with_items: "{{ define_new_user }}"
  tags:
    - common:setup

- name: ======
  copy: src=ssh/sshd_config dest=/etc/ssh/ mode=0600
  become: yes
  notify:
    - restart service

- name: ======
  copy: src=sudo/prov dest=/etc/sudoers.d/ mode=0440
  become: yes

- name: ======
  user:
    name: "{{ item.0.name }}"
    groups: "{{ item.1 }}"
  become: yes
  with_subelements:
    - "{{ define_new_user }}"
    - groups

- name: ======
  authorized_key: user={{ item.0.name }} key={{ item.1 }} exclusive=no
  become: yes
  with_subelements:
    - "{{ define_new_user }}"
    - key